In [2]:
import pandas as pd
import numpy 
import matplotlib.pyplot as plt
import seaborn as sns
import datetime
import math
import matplotlib


#1st Answer

In [9]:
Array = numpy.empty([4,2], dtype = numpy.uint16) 
print("Printing Array")
print(Array)

print("Printing numpy array Attributes")
print("1> Array Shape is: ", Array.shape)
print("2>. Array dimensions are ", Array.ndim)
print("3>. Length of each element of array in bytes is ", Array.itemsize)


Printing Array
[[1 0]
 [1 0]
 [1 0]
 [0 0]]
Printing numpy array Attributes
1> Array Shape is:  (4, 2)
2>. Array dimensions are  2
3>. Length of each element of array in bytes is  2


#2nd answer

In [ ]:

print("Creating 5X2 array using numpy.arange")
Array1 = numpy.arange(100, 200, 10)
Array1 = Array1.reshape(5,2)
print (Array1)

#4th answer

In [5]:
a = numpy.zeros([5,5])
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#5th answer

In [6]:
b=numpy.ones(4)
print(b)

[1. 1. 1. 1.]


#6th answer

In [4]:

c=numpy.matrix('1 2;3 4; 5 6')
c

matrix([[1, 2],
        [3, 4],
        [5, 6]])

#7th answer

In [22]:
x = numpy.arange(100)

x = numpy.reshape(x, (5,2,5,2))
x

array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7],
         [ 8,  9]],

        [[10, 11],
         [12, 13],
         [14, 15],
         [16, 17],
         [18, 19]]],


       [[[20, 21],
         [22, 23],
         [24, 25],
         [26, 27],
         [28, 29]],

        [[30, 31],
         [32, 33],
         [34, 35],
         [36, 37],
         [38, 39]]],


       [[[40, 41],
         [42, 43],
         [44, 45],
         [46, 47],
         [48, 49]],

        [[50, 51],
         [52, 53],
         [54, 55],
         [56, 57],
         [58, 59]]],


       [[[60, 61],
         [62, 63],
         [64, 65],
         [66, 67],
         [68, 69]],

        [[70, 71],
         [72, 73],
         [74, 75],
         [76, 77],
         [78, 79]]],


       [[[80, 81],
         [82, 83],
         [84, 85],
         [86, 87],
         [88, 89]],

        [[90, 91],
         [92, 93],
         [94, 95],
         [96, 97],
         [98, 99]]]])

#3rd answer

In [23]:
y=numpy.matrix('1 2 3;4 5 6;7 8 9')

In [24]:
y

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [25]:
p=y[1]

In [26]:
p

matrix([[4, 5, 6]])

In [28]:
q=y[2]
q

matrix([[7, 8, 9]])

In [30]:
add=numpy.add(p,q)
add

matrix([[11, 13, 15]])

In [31]:
sub=numpy.subtract(p,q)
sub

matrix([[-3, -3, -3]])

In [32]:
mul=numpy.multiply(p,q)
mul

matrix([[28, 40, 54]])

In [33]:
div=numpy.divide(p,q)
div

matrix([[0.57142857, 0.625     , 0.66666667]])